# Generated by Django 2.2.13 on 2020-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherloginsystem', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
