# Generated by Django 2.2.13 on 2020-06-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherloginsystem', '0003_questions_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer10',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer6',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer7',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer8',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer9',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='options10',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='options2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='options3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='options4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='options5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='options6',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='options7',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='options8',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='options9',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='password_for_quiz',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='question10',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='question2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='question3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='question4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='question5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='question6',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='question7',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='question8',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='question9',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='options1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question1',
            field=models.CharField(default='', max_length=500),
        ),
    ]
