# Generated by Django 2.2.13 on 2020-06-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherloginsystem', '0004_auto_20200616_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='studentsid',
            field=models.CharField(default='', max_length=500),
        ),
    ]
