# Generated by Django 2.2.13 on 2020-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherloginsystem', '0005_questions_studentsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=500)),
                ('regNumber', models.CharField(default='', max_length=500)),
                ('password', models.CharField(default='', max_length=500)),
                ('score', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='password_for_quiz',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
